### ISSUE TITLE
Doesn't seem to work on Linux

### ISSUE THREAD

**Issue by GeorgS** [nettantra/grunt-patch#1]
I am using `grunt-patch` on OSX which works fine but if I try to run grunt on my ubuntu server it seems like the plugin doesn't work. I don't get any errors tough, it doesn't do anything at all.

Is this tested on linux?

**Comment by bonesoul** [comment]
Not working for me on windows too

**Comment by GeekTantra** [comment]
Yes this is tested in Linux. Please provide more details.
