### ISSUE TITLE
Failing to patch does not fail the task

### ISSUE THREAD

**Issue by kmudrick** [nettantra/grunt-patch#2]
Running "patch:mypatch" (patch) task

> > Patch failed. Please check your patch and its corresponding version.

I had an error - would have expected the task itself to fail, but grunt continued on its merry way.  Is that because you are returning false in this situation from within the files for loop?

**Comment by Pross** [comment]
Added a PR for this

https://github.com/nettantra/grunt-patch/pull/7

**Comment by tzahari** [comment]
I think this is already fixed with #10
